# Generated by Django 4.1 on 2022-08-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebrandcategory',
            options={'verbose_name': 'Марка устройства', 'verbose_name_plural': 'Марки устройства'},
        ),
        migrations.AlterModelOptions(
            name='devicetypecategory',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Типы устройства'},
        ),
        migrations.AlterModelOptions(
            name='parttypecategory',
            options={'verbose_name': 'Тип запчасти', 'verbose_name_plural': 'Типы запчасти'},
        ),
    ]
