# Generated by Django 4.1 on 2022-08-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_alter_devicebrandcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device_brand_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='e_commerce_app.devicebrandcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_type_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='e_commerce_app.devicetypecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_type_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='e_commerce_app.parttypecategory'),
        ),
    ]
