# Generated by Django 4.1 on 2022-10-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
