# Generated by Django 4.1 on 2022-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_greatest',
            field=models.BooleanField(default=False),
        ),
    ]
