# Generated by Django 4.0.6 on 2022-08-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='e_commerce_app.discount'),
        ),
    ]
