# Generated by Django 4.1 on 2022-08-17 04:30

from django.db import migrations, models
import django.utils.timezone
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_alter_product_device_brand_category_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='orderdetail',
            name='expected_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
