# Generated by Django 4.1 on 2022-08-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_remove_productcategory_is_greatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_greatest',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='quantity',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
