# Generated by Django 4.1 on 2022-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_remove_shoppingsession_total_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
    ]
