# Generated by Django 4.1 on 2022-08-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_productcategory_is_greatest_productcategory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_greatest',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='quantity',
        ),
    ]
