# Generated by Django 4.1 on 2022-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0006_remove_orderdetail_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='status',
            new_name='completed_status',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='delivery_type',
            field=models.CharField(choices=[('COURIER', 'Курьер'), ('PICKUP', 'Самовывоз')], default='COURIER', max_length=30),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment_option',
            field=models.CharField(choices=[('KASPI', 'Kaspi перевод'), ('CASH', 'Наличные')], default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
