# Generated by Django 4.1 on 2022-08-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0006_remove_productcategory_is_greatest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='e_commerce_app.productcategory'),
        ),
    ]
