# Generated by Django 4.1 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_rename_status_orderdetail_completed_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_order',
            field=models.CharField(choices=[('AT_PICKUP', 'После получения'), ('ONLINE', 'Через интернет')], default='AT_PICKUP', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_status',
            field=models.CharField(choices=[('SUCCESSFUL', 'Оплачено'), ('PENDING', 'Ожидается'), ('UNPAID', 'Не оплачено')], default='PENDING', max_length=30),
        ),
    ]
