# Generated by Django 4.1 on 2022-08-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_greatest',
            field=models.BooleanField(default=False),
        ),
    ]
