# Generated by Django 4.1 on 2022-08-08 12:36

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0009_remove_productcategory_is_greatest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=mptt.fields.TreeForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='e_commerce_app.productcategory'),
        ),
    ]
